config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  root to: "home#index"
  resources :jobs do
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users do
    collection do
      get 'search'
      get 'favorite'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates_uniqueness_of :job_id, scope: :user_id
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :username, presence: true

  def already_favorited?(job)
    self.favorites.exists?(job_id: job.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def create
    @favorite = current_user.favorites.create(job_id: params[:job_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @job = Job.find(params[:job_id])
    @favorite = current_user.favorites.find_by(job_id: @job.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.order("id DESC").limit(6)
    @users = User.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_q, only: [:index, :search]
  before_action :authenticate_user!, only: [:show, :create]
  def new
    @job = Job.new
  end
  def create
    @job = Job.new(job_params)
    # @job = current_user.jobs.build(job_params)
    if @job.save
      redirect_to job_path(@job), notice: "投稿に成功しました。"
    else
      render :new
    end
  end
  def index
    
    @jobs = Job.page(params[:page]).per(6).order('id DESC')
  end
  def show
    @job = Job.find(params[:id])
    # @user = User.find(params[:id])
    @jobs = Job.order("id DESC").limit(5)
    @favorite = Favorite.new
  end
  def edit
    @job = Job.find(params[:id])
    if @job.user != current_user
        redirect_to jobs_path, alert: "不正なアクセスです。"
    end
  end
  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to job_path(@job), notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.destroy
    redirect_to user_path(job.user), notice: "投稿を削除しました。"
  end
  def search
    @results = @q.result
    @jobs = Job.page(params[:page]).per(6).order('id DESC')
    
  end

  private
  def set_q
    @q = Job.ransack(params[:q])
  end

  def job_params
    params.require(:job).permit(:title, :body,).merge(user_id: current_user.id)
  end

  def user_params
    params.require(:user).permit(:username, :email, :profile)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_q, only: [:index, :search]
  before_action :authenticate_user!, only: [:show, :create]
  def index
    @users = User.page(params[:page]).per(6).order('id DESC')
    @jobs = Job.page(params[:page]).per(6).order('id DESC')
  end
  def show
    @user = User.find(params[:id])
    @jobs = Job.page(params[:page]).per(4).order('id DESC')
  end
  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def search
    @results = @q.result
    @users = User.page(params[:page]).per(6).order('id DESC')
    
  end
  def favorite
    favorites = Favorite.where(user_id: current_user.id).pluck(:job_id) 
    @favorite_list = Job.find(favorites) 
    @jobs = Job.page(params[:page]).per(4).order('id DESC')
  end
  private
  def set_q
    @q = User.ransack(params[:q])
  end

  def user_params
    params.require(:user).permit(:username, :email, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class='section1'>
  <article class='media'>
    <div class='media-content'>
      <div class='content has-text-centered'>
        <p>
          <strong class='is-size-1' style='font-family: cursive;'>Hello</strong>
        </p>
        <p>ようこそHelloへ。このサイトは在留外国人の方向けの求人紹介サイトになります。</p>
        <br>
        <p>Helloに登録されている全ての企業で外国人の方の採用を行なっております。
      </div>
      <div class='columns is-centered'>
        <div class='column is-5'>
          <%if user_signed_in?%>

          <%else%>
            <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
            <br>
            <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
          <%end%>
          </div>
      </div>
    </div>
  </article>
</section>
<section class='section'>
  <div class='post__new'>
    新着求人6
  </div>
  <div class="container">
    <div class="columns is-multiline">
      <% @jobs.each do |job| %>
        <div class="column is-4">
          <div class="card">
            <div class="title">
              <%= link_to job_path(job) do %>
                <div class="job-title"><%= job.title %></div>
              <% end %>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">

                </div>
                <div class="media-content">
                投稿者
                  <div class="username"><%=link_to job.user.username, user_path(job.user) %></div>
                </div>
              </div>
              <div class="content">
                <time><%= job.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                <tr>
                  <td>
                    <% if user_signed_in? &&current_user.already_favorited?(job) %>
                      <%= link_to job_favorites_path(job), method: :delete do %>
                        <i class="fas fa-heart"></i>
                      <% end %>
                      <%= job.favorites.count %>
                    <% else %>
                      <%= link_to job_favorites_path(job), method: :post do %>
                        <i class="far fa-heart"></i>
                      <% end %>
                      <%= job.favorites.count %>
                    <% end %>
                  </td>
                </tr>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/jobs/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        求人編集
      </h1>
    </div>
  </div>
</section>

<% if @job.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@job.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @job do |f| %>
          <div class="field">
            <%= f.label :title, "仕事名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        求人一覧
      </h1>
      <h1>仕事検索</h1>
      <%= search_form_for @q, url: search_jobs_path do |f| %>
      <div class="navbar-left">
        <div class="navbar-item">
          <div class="field has-addons">
            <div class="control">
              <%= f.search_field :title_cont ,class: 'input'%>
            </div>
            <div class="control">
              <%= f.submit '検索', class: 'button is-info' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @jobs.each do |job| %>
        <div class="column is-4">
          <div class="card">
            <div class="title">
              <%= link_to job_path(job) do %>
                <div class="job-title"><%= job.title %></div>
              <% end %>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                </div>
                <div class="media-content">
                投稿者
                  <div class="username"><%=link_to job.user.username, user_path(job.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= job.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                <tr>
                  <td>
                    <% if user_signed_in? &&current_user.already_favorited?(job) %>
                      <%= link_to job_favorites_path(job), method: :delete do %>
                        <i class="fas fa-heart"></i>
                      <% end %>
                      <%= job.favorites.count %>
                    <% else %>
                      <%= link_to job_favorites_path(job), method: :post do %>
                        <i class="far fa-heart"></i>
                      <% end %>
                      <%= job.favorites.count %>
                    <% end %>
                  </td>
                </tr>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @jobs %>
    </div>
  </div>
</section>

app/views/jobs/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        求人作成
      </h1>
    </div>
  </div>
</section>


<% if @job.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@job.errors.count, "error") %> 全ての項目に入力してください</h2>
    <ul>
      <% @job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @job do |f| %>
          <div class="field">
            <%= f.label :title, "職種", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "詳細　(業務詳細、連絡先のメールアドレスやお電話番号を記入してください）", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/jobs/search.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        検索結果
      </h1>
</section>
<table>
  <tbody>
  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
      <% if @results.any? %>
        <% @results.each do |job| %>
          <div class="column is-4">
            <div class="card">
              <div class="title">
                <%= link_to job_path(job) do %>
                  <div class="job-title"><%= job.title %></div>
                <% end %>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">

                  </div>
                  <div class="media-content">
                  投稿者
                    <div class="username"><%=link_to job.user.username, user_path(job.user) %></div>
                  </div>
                </div>

                <div class="content">
                  <time><%= job.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                </div>
              </div>
            </div>
          </div>
        <% end %>
          <%= paginate @jobs %>
      <% else %>
      <h3><%= '検索結果がありません。' %></h3>
      <% end %>
  </tbody>
</table>

app/views/jobs/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        求人詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-contents">
                <p class="title is-4"><%= @job.title %></p>
                  <tr>
                    <td>
                      <% if user_signed_in? &&current_user.already_favorited?(@job) %>
                        <%= link_to job_favorites_path(@job), method: :delete do %>
                          <i class="fas fa-heart"></i>
                        <% end %>
                        <%= @job.favorites.count %>
                      <% else %>
                        <%= link_to job_favorites_path(@job), method: :post do %>
                          <i class="far fa-heart"></i>
                        <% end %>
                        <%= @job.favorites.count %>
                      <% end %>
                    </td>
                  </tr>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>求人情報</th>
                </tr>
                <tr>
                  <td><%= simple_format @job.body %></td>
                </tr>
              </table>
              <% if user_signed_in? && current_user.id == @job.user_id %>
                <%= link_to "編集画面へ", edit_job_path(@job), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">Hello</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "求人一覧", jobs_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "求人投稿", new_job_path, class: "navbar-item button is-warning is-light" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "企業、会社一覧", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "求人一覧", jobs_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "投稿者一覧", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> ユーザー名またはメールアドレスが入力されていません</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/favorite.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        いいねしたお仕事一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% if @favorite_list.present? %>
        <% @favorite_list.each do |job| %>
          <div class="column is-4">
            <div class="card">
              <div class="title">
                <%= link_to job_path(job) do %>
                  <div class="job-title"><%= job.title %></div>
                <% end %>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                  </div>
                  <div class="media-content">
                  投稿者
                    <div class="username"><%=link_to job.user.username, user_path(job.user) %></div>
                  </div>
                </div>
              </div>
            </div>
          </div> 
        <% end %>
      <% end %>
      <%= paginate @jobs %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        企業一覧
      </h1>
      <h1>企業検索</h1>
      <%= search_form_for @q, url: search_users_path do |f| %>
      <div class="navbar-left">
        <div class="navbar-item">
          <div class="field has-addons">
            <div class="control">
              <%= f.search_field :username_cont ,class: 'input'%>
            </div>
            <div class="control">
              <%= f.submit '検索', class: 'button is-info' %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.jobs.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @jobs %>
    </div>
  </div>
</section>

app/views/users/search.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        検索結果
      </h1>
</section>
<table>
  <tbody>
  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
      <% if @results.any? %>
        <% @results.each do |user| %>
          <div class="column is-3">
            <div class="card">
              <div class="card-content">
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <div class="title"><%=link_to user.username, user_path(user) %></div>
                  </div>
                </div>
                <div class="content">
                  投稿数：<%= user.jobs.count %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
          <%= paginate @users %>
      <% else %>
      <h3><%= '検索結果がありません。' %></h3>
      <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-10">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if user_signed_in? &&@user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <td>
                    <%= link_to 'いいねしたお仕事',favorite_users_path(@user), class: "button is-warning" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.jobs.each do |job| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <div class="mypage-job-title"><%= job.title %></div>
              <div class="media">
                <div class="media-content">
                  <%= link_to job_path(job), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この求人を見る
                  <% end %>
                  <% if user_signed_in? &&@user.id == current_user.id %>
                    <%= link_to edit_job_path(job), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この求人を編集する
                    <% end %>
                    <%= link_to job_path(job), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この求人を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= job.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>